### ISSUE TITLE
Update Klaxon for compatibility with gradle 7.x

### ISSUE THREAD

**Issue by sideisra** [mayope/deployment-plugin#3]
When updating the build to gradle 7.x I get the following error:  Could not find com.beust:klaxon:5.2.

It seems to be related to the deprecation of jcenter repository. The availability of the klaxon library in plugins.gradle.org starts with version 5.4. Could klaxon be updated to at least version 5.4?

**Comment by klg71** [comment]
Hey @sideisra thanks for bringing it up :) Could you test version 0.0.62?

**Comment by sideisra** [comment]
@klg71 I don't see a version 0.0.62. The latest version seems to be 0.0.61,

**Comment by klg71** [comment]
Sry typo its the  0.0.61

**Comment by sideisra** [comment]
Does version 0.0.61 need java 17?

**Comment by klg71** [comment]
It is build with java 17 but I did hope it would work with lower versions too.
